package player;

public enum PlayerSprite {
	DEFAULT_DEFAULT,
	DEFAULT_MOVING,
	DEFAULT_TRANSITION,
	SWORD_DEFAULT,
	SWORD_MOVING,
	SWORD_TRANSITION,
	SHIELD_DEFAULT,
	SHIELD_MOVING,
	SHIELD_TRANSITION,
}
